---
- name: Deploy erimodo bot
  hosts: all
  become: yes

  vars:
    erimodo_dir: /home/tbellavia/Erimodo

  tasks:
    - name: Pull repository
      ansible.builtin.git:
        repo: https://github.com/Cardiox12/erimodo.git
        clone: true
        dest: "{{ erimodo_dir }}"
        update: true

    - name: Remove previous containers
      ansible.builtin.command: 
        cmd: docker-compose down --volumes
        chdir: "{{ erimodo_dir }}"
      ignore_errors: true

    - name: Run docker compose
      ansible.builtin.command: 
        cmd: docker-compose up -d
        chdir: "{{ erimodo_dir }}"
      